object Versions {

    const val core = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val annotation = "1.3.0"
    const val lifecycle = "2.4.0"
    const val dataBinding = "7.0.4"
    const val junit = "4.+"
    const val junitTest = "1.1.3"
    const val espresso = "3.4.0"
    const val hilt = "2.40"
    const val hiltCompiler = "2.38.1"
    const val timber = "5.0.1"
    const val room = "2.4.1"
    const val retrofit2 = "2.9.0"
    const val loggingInterceptor = "4.9.0"
    const val coroutines = "1.6.0"
    const val activity = "1.4.0"
    const val fragment = "1.4.1"
    const val firebaseBom = "29.0.4"
    const val gradlePlugin = "7.0.4"
    const val kotlin = "1.6.10"
    const val googleServices = "4.3.10"
    const val firebaseCrashlytics = "2.8.1"
    const val navVersion = "2.4.2"
    const val splashScreen = "1.0.0-beta02"


}